all: runHello runHelloEvil runHelloLocal

runHello: 01-helloWorld.c
	g++ 01-helloWorld.c -o runHello

runHelloEvil: 02-helloWorldEvil.c
	g++ 02-helloWorldEvil.c -o runHelloEvil

runHelloLocal: 03-helloWorldLocal.c
	g++ 03-helloWorldLocal.c -o runHelloLocal

